
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 23 18:44:40 CET 2011
//----------------------------------------------------

package microJava;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ASSIGNMENT = 27;
  public static final int NOT_EQUAL = 20;
  public static final int LPAREN = 33;
  public static final int GREATER = 21;
  public static final int SEMI = 30;
  public static final int LESS = 23;
  public static final int INVALID = 2;
  public static final int MINUS = 15;
  public static final int RPAREN = 34;
  public static final int AND = 25;
  public static final int OR = 26;
  public static final int COMMA = 31;
  public static final int CLASS = 3;
  public static final int INC = 28;
  public static final int DIV = 17;
  public static final int LESS_EQUAL = 24;
  public static final int PLUS = 14;
  public static final int IF = 9;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 19;
  public static final int GREATER_EQUAL = 22;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int NUMBER = 39;
  public static final int MOD = 18;
  public static final int IDENT = 41;
  public static final int BREAK = 13;
  public static final int VOID = 5;
  public static final int TIMES = 16;
  public static final int LBRACE = 37;
  public static final int ELSE = 10;
  public static final int LSQUARE = 35;
  public static final int READ = 7;
  public static final int CHARCONST = 40;
  public static final int RSQUARE = 36;
  public static final int FINAL = 4;
  public static final int WHILE = 11;
  public static final int RBRACE = 38;
  public static final int DEC = 29;
  public static final int PRINT = 6;
}

